"""
Report Bridge - PDF and Markdown Report Generation

Generates audit reports, trade journals, and performance summaries.
Wraps reportlab (PDF) and markdown libraries.

Follows Rule 14: Configuration Over Code - templates in config/
"""

import logging
from typing import Dict, List, Any, Optional
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

logger = logging.getLogger("inspector.report_bridge")


@dataclass
class ReportSection:
    """Single section of a report."""
    title: str
    content: str
    level: int = 2  # Heading level (1-4)


@dataclass
class ReportData:
    """Data for generating a report."""
    title: str
    report_type: str  # "audit", "journal", "weekly", "performance"
    sections: List[ReportSection]
    metadata: Dict[str, Any] = None
    generated_at: str = None

    def __post_init__(self):
        if self.generated_at is None:
            self.generated_at = datetime.utcnow().isoformat()
        if self.metadata is None:
            self.metadata = {}


class ReportBridge:
    """
    Bridge for generating reports in PDF and Markdown formats.

    Templates are loaded from config/templates/ (Rule 14).
    """

    def __init__(self, output_dir: str = "storage/reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_markdown(self, data: ReportData) -> str:
        """
        Generate Markdown report.

        Args:
            data: ReportData with sections to render.

        Returns:
            Path to generated .md file.
        """
        lines = [
            f"# {data.title}",
            "",
            f"**Type**: {data.report_type}",
            f"**Generated**: {data.generated_at}",
            "",
            "---",
            ""
        ]

        # Add metadata if present
        if data.metadata:
            lines.append("## Summary")
            lines.append("")
            for key, value in data.metadata.items():
                lines.append(f"- **{key}**: {value}")
            lines.append("")
            lines.append("---")
            lines.append("")

        # Add sections
        for section in data.sections:
            heading = "#" * section.level
            lines.append(f"{heading} {section.title}")
            lines.append("")
            lines.append(section.content)
            lines.append("")

        # Footer
        lines.extend([
            "---",
            "",
            "*Generated by Vulcan Inspector Bot*"
        ])

        # Write file
        filename = self._generate_filename(data, "md")
        filepath = self.output_dir / filename

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        logger.info(f"Generated Markdown report: {filepath}")
        return str(filepath)

    def generate_pdf(self, data: ReportData) -> Optional[str]:
        """
        Generate PDF report using reportlab.

        Args:
            data: ReportData with sections to render.

        Returns:
            Path to generated .pdf file, or None if reportlab unavailable.
        """
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.styles import getSampleStyleSheet
        except ImportError:
            logger.warning("reportlab not installed - falling back to Markdown")
            return self.generate_markdown(data)

        filename = self._generate_filename(data, "pdf")
        filepath = self.output_dir / filename

        doc = SimpleDocTemplate(str(filepath), pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Title
        story.append(Paragraph(data.title, styles["Title"]))
        story.append(Spacer(1, 12))

        # Metadata
        story.append(Paragraph(f"Type: {data.report_type}", styles["Normal"]))
        story.append(Paragraph(f"Generated: {data.generated_at}", styles["Normal"]))
        story.append(Spacer(1, 12))

        # Sections
        for section in data.sections:
            style = styles[f"Heading{min(section.level, 3)}"]
            story.append(Paragraph(section.title, style))
            story.append(Spacer(1, 6))
            story.append(Paragraph(section.content, styles["Normal"]))
            story.append(Spacer(1, 12))

        doc.build(story)
        logger.info(f"Generated PDF report: {filepath}")
        return str(filepath)

    def generate_trade_journal(self, trades: List[Dict]) -> str:
        """Generate trade journal report from trade records."""
        sections = []

        # Summary section
        wins = sum(1 for t in trades if t.get("result") == "win")
        losses = sum(1 for t in trades if t.get("result") == "loss")
        total_r = sum(t.get("r_multiple", 0) for t in trades)

        summary = f"""
- **Total Trades**: {len(trades)}
- **Wins**: {wins} | **Losses**: {losses}
- **Win Rate**: {(wins/len(trades)*100) if trades else 0:.1f}%
- **Total R**: {total_r:.2f}
"""
        sections.append(ReportSection("Performance Summary", summary.strip()))

        # Individual trades
        for trade in trades:
            content = f"""
- **Pair**: {trade.get('pair', 'N/A')}
- **Setup**: {trade.get('setup_type', 'N/A')}
- **Result**: {trade.get('result', 'N/A')} ({trade.get('r_multiple', 0)}R)
- **Lesson**: {trade.get('lesson', 'None recorded')}
"""
            sections.append(ReportSection(
                f"Trade: {trade.get('id', 'Unknown')}",
                content.strip(),
                level=3
            ))

        data = ReportData(
            title="Trade Journal",
            report_type="journal",
            sections=sections,
            metadata={"total_trades": len(trades), "win_rate": f"{(wins/len(trades)*100) if trades else 0:.1f}%"}
        )

        return self.generate_markdown(data)

    def generate_audit_report(self, audits: List[Dict]) -> str:
        """Generate audit summary report."""
        sections = []

        for audit in audits:
            content = f"""
**Grade**: {audit.get('grade', 'N/A')} ({audit.get('score', 0)}/100)

**Findings**:
{self._list_to_bullets(audit.get('findings', []))}

**Recommendations**:
{self._list_to_bullets(audit.get('recommendations', []))}
"""
            sections.append(ReportSection(
                f"Audit: {audit.get('item_id', 'Unknown')}",
                content.strip(),
                level=3
            ))

        data = ReportData(
            title="Audit Report",
            report_type="audit",
            sections=sections
        )

        return self.generate_markdown(data)

    def _generate_filename(self, data: ReportData, ext: str) -> str:
        """Generate timestamped filename."""
        timestamp = datetime.utcnow().strftime("%Y-%m-%d_%H%M%S")
        safe_type = data.report_type.replace(" ", "_")
        return f"{safe_type}_{timestamp}.{ext}"

    def _list_to_bullets(self, items: List[str]) -> str:
        """Convert list to markdown bullets."""
        if not items:
            return "- None"
        return "\n".join(f"- {item}" for item in items)
